#Isaac Aguilar          9-4-2025
#Zany Texts Assessment
print("Zany Wany Fany Texts Assessment!")
print()
print("By Isaac Aguilar") 
print("[Coms 1270 4]") 
print()
print("Zany Texts #1!") 
print()
adjective1=input("please enter a adjective") 
noun1=input("please enter a noun")
adjective2=input("please enter another adjective")
noun2=input("please eneter another noun")
verb1=input("please enter a verb")
emotion1=input("please enter a emotion")
verb2=input("please enter another verb")

print("1,000",adjective1,noun1,"are fighting 2,000",adjective2,noun2,".the",noun1,"are",verb1,"away from",noun2, "because they are",emotion1,"towards the",noun2,".But the",noun2,"continue",verb2,"towards",noun1,
    "to win this battle.In the end the",noun2,"won the battle of the greats by a hair, and this tale will be told for years and years.")
print("-----------------------")
print("Zany Texts #2!")
print()
Name1=input("please enter a name")
Location1=input("please enter a location")
Adjective3=input("please enter a adjective")
Noun3=input("please enter a noun")
Size1=input("please enter a size")
Adjective4=input("please eneter another adjective")
Noun4=input("please enter another noun")
Emotion2=input("please enter a emotion")
Noun5=input("please enter another noun")

print("One day",Name1,"was exploring",Location1,".",Name1,"found many great wonders like a", Adjective3,Noun3,"and a", Size1,Adjective4,Noun4,".As",Name1,"continued on their journey they began to feel"
      ,Emotion2,"from all the exploring.Eventually",Name1,"left",Location1,",but as they left they found a 1 of a kind",Noun5,"and took it home with them.")
print("---------------------")
print("Zany Texts #3!")
print()
Number1=input("please enter a number between 100-1000")
Animal1=input("please enter a animal")
Number2=input ("please enter another number between 100-1000")
Verb3=input("please enter a verb")
PresentParticipleAdjective5=input ("please enter a presnt participle adjective")
Villian=input("please enter a super-villian")
Number3=input("please enter another number between 100-1000") 

print("Would you rather fight",Number1,Animal1,"or swim",Number2,"miles? Well turns out you have to do both, unless you want to take the risky 3rd option of",Verb3,"through a", PresentParticipleAdjective5,"building while", 
      Villian,"Chases you? However, if you do survive you also win",Number3,"million dollars! What do you choose?")
print("----------------------")
print("Zany Texts #4!")
print()
Name2=input("please enter a name")
Name3=input("please enter another name")
Color1=input("please enter a color")
Animal2=input("please enter a animal")
Game1=input("please enter a carnival game")
Game2=input("please enter another carnival game")
print("At a carnival", Name2,"won a", Color1,Animal2,"stuffed animal when playing",Game1,".", Name3,"knew he could beat",Name2,"so they played",Game2, "and won and got a bigger",Color1,Animal2, "." )
